name: "HOTFIX to Workshop"

on:
  pull_request_target:
    branches:
      - main
    types: [closed]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: hotfix-${{ github.ref }}
  cancel-in-progress: false

jobs:
  hotfix:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout trusted merge commit
        uses: actions/checkout@v4
        with:
          # Checkout the merge commit that now lives on main (trusted), not the PR head.
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          persist-credentials: false

      - name: Publish to Steam Workshop
        uses: AnarkisGaming/workshop@v1
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
        with:
          appID: "108600"
          # publishedFileID -- workshop ID
          publishedFileID: "3285160052"
          # changelog: 'log of changes'
          path: Contents
